apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-prometheus-exporter.fullname" . }}
  labels:
    {{- include "s3-prometheus-exporter.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app.kubernetes.io/name: {{ include "s3-prometheus-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP